[package]
name = "akidocs-core-rs"
version = "0.0.0-dev"
edition = "2024"

[[bin]]
name = "akir"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
genpdf = "0.2.0"

[dev-dependencies]
assert_cmd = "2.1.1"
